### ISSUE TITLE
Cross platform

### ISSUE THREAD

**Issue by thearian** [thearian/volu#1]
The first version is released but only for `windows`   
We'll need other platforms too

**Wanted platform:**
- [x] x86_64-pc-windows-msvc
- [x] x86_64-apple-darwin
- [x] x86_64-unknown-linux-gnu
- [x] x86_64-unknown-linux-musl

**Comment by mattrosewood** [comment]
Hi @thearian, I've resolved it here #2.

**Comment by thearian** [comment]
Got it. Thanks!
